/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.example;

public class App {

    public static void main(String[] args) {
        LibraryA libA = new LibraryA();
        LibraryB libB = new LibraryB();

        System.out.println(libA.message());
        System.out.println(libB.message());
    }

}
