/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class LibraryA {
    public String message() {
        return this.getClass().getSimpleName();
    }
}
